# syntax=docker/dockerfile:1.7

FROM golang:1.25-bookworm AS builder

WORKDIR /src

COPY UrlShortener/go.mod UrlShortener/go.sum ./

RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY UrlShortener/ ./

ARG TARGETOS=linux
ARG TARGETARCH=amd64

RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 \
    GOOS=${TARGETOS} \
    GOARCH=${TARGETARCH} \
    go build \
      -trimpath \
      -ldflags="-s -w" \
      -o /out/url-shortener \
      ./cmd/url-shortener

FROM gcr.io/distroless/base-debian12:nonroot

WORKDIR /app
COPY --from=builder /out/url-shortener /usr/local/bin/url-shortener

EXPOSE 18081

STOPSIGNAL SIGTERM
ENTRYPOINT ["/usr/local/bin/url-shortener"]
