import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  message: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 12,
  },
  userMessage: {
    alignSelf: "flex-end",
    backgroundColor: "#b9e9b0",
    borderColor: "#8ebd84",
    maxWidth: "92%",
  },
  assistantMessage: {
    alignSelf: "stretch",
    backgroundColor: "#fffaf0",
    borderColor: "#e0d8ca",
  },
  assistantLoadingMessage: {
    alignItems: "center",
    flexDirection: "row",
    minHeight: 46,
  },
  assistantLoadingLabel: {
    alignSelf: "flex-start",
    minWidth: 92,
    overflow: "hidden",
    position: "relative",
  },
  assistantLoadingText: {
    color: "#b5afa7",
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 20,
  },
  assistantLoadingSoftWindow: {
    left: 0,
    overflow: "hidden",
    pointerEvents: "none",
    position: "absolute",
    top: 0,
    width: 34,
  },
  assistantLoadingSoftText: {
    color: "#7d766f",
  },
  assistantLoadingHighlightWindow: {
    left: 0,
    overflow: "hidden",
    pointerEvents: "none",
    position: "absolute",
    top: 0,
    width: 16,
  },
  assistantLoadingHighlightText: {
    color: "#36312d",
  },
  eventMessage: {
    alignSelf: "stretch",
    backgroundColor: "#ffd84f",
    borderColor: "#e2b936",
  },
  toolMessage: {
    alignSelf: "stretch",
    backgroundColor: "#4fd7ee",
    borderColor: "#a1d9e3",
    gap: 8,
  },
  errorMessage: {
    alignSelf: "stretch",
    backgroundColor: "#ff7f68",
    borderColor: "#d56c5b",
  },
  messageText: {
    color: "#12100e",
    lineHeight: 20,
  },
  messageMeta: {
    color: "#6c665f",
    fontSize: 11,
    marginTop: 8,
  },
  messageStatusRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  messageStatusPill: {
    backgroundColor: "#ffd84f",
    borderColor: "#12100e",
    borderRadius: 6,
    borderWidth: 1,
    color: "#12100e",
    fontSize: 10,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 4,
    textTransform: "uppercase",
  },
  regenerateButton: {
    backgroundColor: "#4fd7ee",
    borderColor: "#12100e",
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  regenerateButtonText: {
    color: "#12100e",
    fontSize: 11,
    fontWeight: "900",
  },
  reasoningBlock: {
    alignSelf: "stretch",
    marginBottom: 8,
    overflow: "hidden",
    position: "relative",
  },
  reasoningHeader: {
    alignItems: "center",
    alignSelf: "flex-start",
    flexDirection: "row",
    gap: 5,
    minHeight: 30,
    paddingVertical: 4,
  },
  reasoningShimmerLabel: {
    minWidth: 0,
  },
  reasoningSummaryText: {
    color: "#8f8982",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 20,
  },
  reasoningChevron: {
    color: "#9b958e",
    fontSize: 16,
    lineHeight: 18,
    textAlign: "center",
    width: 18,
  },
  reasoningBodyClip: {
    overflow: "hidden",
  },
  reasoningBody: {
    borderLeftColor: "#d6d0c8",
    borderLeftWidth: 2,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingTop: 4,
  },
  reasoningBodyMeasure: {
    left: 0,
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    right: 0,
    top: 30,
  },
  reasoningText: {
    color: "#6c665f",
    fontSize: 12,
    lineHeight: 18,
  },
  toolHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  toolBadge: {
    backgroundColor: "#ffd84f",
    borderColor: "#12100e",
    borderRadius: 6,
    borderWidth: 1,
    color: "#12100e",
    fontSize: 10,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 4,
    textAlign: "center",
    width: 44,
  },
  toolTitle: {
    color: "#12100e",
    fontSize: 13,
    fontWeight: "900",
  },
  toolSubtitle: {
    color: "#12100e",
    fontSize: 11,
    marginTop: 2,
  },
  toolToggle: {
    color: "#12100e",
    fontSize: 12,
    fontWeight: "900",
  },
  toolBody: {
    borderTopColor: "#d7cfc2",
    borderTopWidth: 1,
    gap: 8,
    paddingTop: 8,
  },
  toolSection: {
    gap: 5,
  },
  toolSectionTitle: {
    color: "#12100e",
    fontSize: 11,
    fontWeight: "900",
  },
  toolCode: {
    color: "#12100e",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    fontSize: 12,
    lineHeight: 18,
  },
  toolErrorText: {
    color: "#7a1f1a",
  },
  toolGroupMessage: {
    alignSelf: "stretch",
    backgroundColor: "#f5f1e9",
    borderColor: "#d7cfc2",
    gap: 8,
  },
  toolGroupHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  toolGroupBadge: {
    backgroundColor: "#ffd84f",
    borderColor: "#12100e",
    borderRadius: 6,
    borderWidth: 2,
    color: "#12100e",
    fontSize: 10,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 4,
    textAlign: "center",
    width: 54,
  },
  toolGroupBadgeError: {
    backgroundColor: "#ff7f68",
  },
  toolGroupTitle: {
    color: "#12100e",
    fontSize: 13,
    fontWeight: "900",
  },
  toolGroupSubtitle: {
    color: "#6c665f",
    fontSize: 11,
    marginTop: 2,
  },
  toolGroupBody: {
    borderTopColor: "#d7cfc2",
    borderTopWidth: 1,
    gap: 8,
    paddingTop: 8,
  },
  toolGroupStep: {
    backgroundColor: "#fffaf0",
    borderColor: "#12100e",
    borderRadius: 8,
    borderWidth: 2,
    gap: 7,
    padding: 8,
  },
  toolGroupStepHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  toolGroupStepBadge: {
    backgroundColor: "#b9e9b0",
    borderColor: "#12100e",
    borderRadius: 5,
    borderWidth: 2,
    color: "#12100e",
    fontSize: 9,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 6,
    paddingVertical: 3,
    textAlign: "center",
    width: 44,
  },
  toolGroupStepBadgeError: {
    backgroundColor: "#ff7f68",
  },
  toolGroupStepTitle: {
    color: "#12100e",
    flex: 1,
    fontSize: 12,
    fontWeight: "900",
  },
  toolGroupStepMeta: {
    color: "#6c665f",
    fontSize: 10,
    fontWeight: "800",
  },
  toolGroupStepSection: {
    gap: 4,
  },
  toolGroupStepLabel: {
    color: "#6c665f",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  toolGroupStepText: {
    color: "#12100e",
    fontSize: 12,
    lineHeight: 18,
  },
  toolGroupCode: {
    color: "#12100e",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    fontSize: 11,
    lineHeight: 16,
  },
  assetCard: {
    alignItems: "center",
    backgroundColor: "#fffaf0",
    borderColor: "#12100e",
    borderRadius: 8,
    borderWidth: 3,
    flexDirection: "row",
    gap: 10,
    padding: 9,
  },
  assetImageCard: {
    alignItems: "stretch",
    flexDirection: "column",
  },
  assetDetailsRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    width: "100%",
  },
  assetPreviewButton: {
    backgroundColor: "#f1ece3",
    borderColor: "#12100e",
    borderRadius: 7,
    borderWidth: 2,
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  assetPreviewImage: {
    aspectRatio: 16 / 9,
    backgroundColor: "#f1ece3",
    width: "100%",
  },
  assetPreviewOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(255, 250, 240, 0.82)",
    bottom: 0,
    gap: 6,
    justifyContent: "center",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  assetPreviewStatus: {
    color: "#6c665f",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 4,
  },
  assetIconBox: {
    alignItems: "center",
    backgroundColor: "#ffd84f",
    borderColor: "#12100e",
    borderRadius: 7,
    borderWidth: 2,
    height: 42,
    justifyContent: "center",
    width: 48,
  },
  assetIconText: {
    color: "#12100e",
    fontSize: 11,
    fontWeight: "900",
  },
  assetContent: {
    flex: 1,
    minWidth: 0,
  },
  assetTitle: {
    color: "#12100e",
    fontSize: 13,
    fontWeight: "900",
  },
  assetPath: {
    color: "#6c665f",
    fontSize: 11,
    marginTop: 2,
  },
  assetMeta: {
    color: "#12100e",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 4,
  },
  assetURL: {
    color: "#2458c7",
    fontSize: 11,
    marginTop: 4,
  },
  assetOpenButton: {
    backgroundColor: "#b9e9b0",
    borderColor: "#12100e",
    borderRadius: 7,
    borderWidth: 2,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  assetOpenButtonText: {
    color: "#12100e",
    fontSize: 11,
    fontWeight: "900",
  },
  markdownRoot: {
    gap: 8,
  },
  markdownHeading: {
    color: "#12100e",
    fontWeight: "900",
  },
  markdownHeading1: {
    fontSize: 20,
    lineHeight: 26,
  },
  markdownHeading2: {
    fontSize: 17,
    lineHeight: 23,
  },
  markdownHeading3: {
    fontSize: 15,
    lineHeight: 21,
  },
  markdownParagraph: {
    color: "#12100e",
    lineHeight: 20,
  },
  markdownStrong: {
    fontWeight: "900",
  },
  markdownEmphasis: {
    fontStyle: "italic",
  },
  markdownInlineCode: {
    backgroundColor: "#f5eefc",
    borderColor: "#12100e",
    borderRadius: 4,
    borderWidth: 1,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    paddingHorizontal: 4,
  },
  markdownList: {
    gap: 6,
  },
  markdownListItem: {
    flexDirection: "row",
    gap: 8,
  },
  markdownListMarker: {
    color: "#12100e",
    fontWeight: "900",
    width: 20,
  },
  markdownListText: {
    color: "#12100e",
    flex: 1,
    lineHeight: 20,
  },
  markdownCodeBlock: {
    backgroundColor: "#f1ece3",
    borderColor: "#12100e",
    borderRadius: 8,
    borderWidth: 2,
    gap: 6,
    padding: 8,
  },
  markdownCodeLabel: {
    color: "#6c665f",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  markdownCodeScroll: {
    maxWidth: "100%",
  },
  markdownCodeText: {
    color: "#12100e",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    fontSize: 12,
    lineHeight: 18,
  },
  markdownTableScroll: {
    maxWidth: "100%",
  },
  markdownTable: {
    borderColor: "#12100e",
    borderRadius: 8,
    borderWidth: 2,
    overflow: "hidden",
  },
  markdownTableHeaderRow: {
    flexDirection: "row",
  },
  markdownTableRow: {
    flexDirection: "row",
  },
  markdownTableRowAlt: {
    backgroundColor: "#f5f1e9",
  },
  markdownTableCell: {
    borderColor: "#12100e",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    minWidth: 120,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  markdownTableHeaderCell: {
    backgroundColor: "#ffd84f",
  },
  markdownTableCellText: {
    color: "#12100e",
    fontSize: 11,
    lineHeight: 17,
  },
  markdownQuote: {
    alignItems: "stretch",
    backgroundColor: "#f5f1e9",
    borderColor: "#12100e",
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: "row",
    gap: 8,
    padding: 8,
  },
  markdownQuoteBar: {
    backgroundColor: "#4fd7ee",
    borderRadius: 3,
    width: 5,
  },
  markdownQuoteText: {
    color: "#12100e",
    lineHeight: 20,
  },
});
