import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    gap: 12,
  },
  panel: {
    backgroundColor: "#fffdf7",
    borderColor: "#12100e",
    borderRadius: 16,
    borderWidth: 2,
    elevation: 3,
    gap: 12,
    padding: 14,
    shadowColor: "#12100e",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  changesPanel: {
    minHeight: 280,
  },
  panelHeader: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "space-between",
  },
  panelTitle: {
    color: "#12100e",
    fontSize: 16,
    fontWeight: "900",
  },
  pathText: {
    color: "#6c665f",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  rowCompact: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  flex: {
    flex: 1,
    minWidth: 0,
  },
  smallButton: {
    alignItems: "center",
    backgroundColor: "#ffd84f",
    borderColor: "#12100e",
    borderRadius: 8,
    borderWidth: 2,
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    elevation: 1,
  },
  disabledButton: {
    opacity: 0.45,
  },
  changeList: {
    gap: 8,
  },
  changeRow: {
    alignItems: "center",
    backgroundColor: "#fffdf7",
    borderColor: "#12100e",
    borderRadius: 12,
    borderWidth: 1.5,
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    elevation: 2,
    shadowColor: "#12100e",
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  changeRowActive: {
    backgroundColor: "#fef3c7",
    borderColor: "#12100e",
  },
  changeBadge: {
    alignItems: "center",
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: "#12100e",
    color: "#12100e",
    fontSize: 12,
    fontWeight: "900",
    height: 26,
    justifyContent: "center",
    lineHeight: 23,
    overflow: "hidden",
    textAlign: "center",
    width: 26,
  },
  changeBadgeModified: {
    backgroundColor: "#ffd84f",
  },
  changeBadgeAdded: {
    backgroundColor: "#b9e9b0",
  },
  changeBadgeDeleted: {
    backgroundColor: "#ff7f68",
  },
  changeBadgeRenamed: {
    backgroundColor: "#4fd7ee",
  },
  fileName: {
    color: "#12100e",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    fontSize: 12.5,
    fontWeight: "800",
  },
  fileDir: {
    color: "#8c857b",
    fontWeight: "500",
  },
  fileMeta: {
    color: "#6c665f",
    fontSize: 11,
    marginTop: 2,
  },
  viewDiffText: {
    color: "#12100e",
    fontSize: 11,
    fontWeight: "800",
  },
  historyBox: {
    backgroundColor: "#fffdf7",
    borderColor: "#12100e",
    borderRadius: 16,
    borderWidth: 2,
    elevation: 3,
    gap: 10,
    padding: 14,
    shadowColor: "#12100e",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  historyList: {
    gap: 8,
  },
  historyRow: {
    backgroundColor: "#fdfbf7",
    borderColor: "#12100e",
    borderRadius: 12,
    borderWidth: 1.5,
    gap: 6,
    padding: 12,
    shadowColor: "#12100e",
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  historyHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  historyTag: {
    color: "#12100e",
    fontSize: 12,
    fontWeight: "900",
  },
  historyCount: {
    color: "#6c665f",
    fontSize: 11,
    fontWeight: "700",
  },
  historyTitle: {
    color: "#12100e",
    fontSize: 13,
    fontWeight: "800",
  },
  historyMeta: {
    color: "#8c857b",
    fontSize: 11,
  },
  historyActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "flex-end",
    marginTop: 4,
  },
  previewHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
  },
  previewTitle: {
    color: "#12100e",
    fontSize: 14,
    fontWeight: "900",
  },
  previewButton: {
    alignItems: "center",
    backgroundColor: "#ffd84f",
    borderColor: "#12100e",
    borderRadius: 8,
    borderWidth: 2,
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  revertButton: {
    alignItems: "center",
    backgroundColor: "#ff7f68",
    borderColor: "#12100e",
    borderRadius: 8,
    borderWidth: 2,
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  emptyText: {
    color: "#6c665f",
    fontSize: 12,
    paddingVertical: 6,
  },
  diffDetailPanel: {
    gap: 12,
  },
  detailHeader: {
    alignItems: "center",
    backgroundColor: "#fffdf7",
    borderColor: "#25231f",
    borderRadius: 14,
    borderWidth: 2,
    elevation: 2,
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  detailBackButton: {
    alignItems: "center",
    backgroundColor: "#fffdf7",
    borderColor: "#12100e",
    borderRadius: 8,
    borderWidth: 2,
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  detailBackText: {
    color: "#12100e",
    fontSize: 12,
    fontWeight: "900",
  },
  detailHeaderCenter: {
    alignItems: "center",
    flex: 1,
    minWidth: 0,
  },
  detailHeaderTitle: {
    color: "#12100e",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    fontSize: 13,
    fontWeight: "900",
  },
  diffStatsBar: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 4,
  },
  diffStatsPath: {
    color: "#6c665f",
    flex: 1,
    fontSize: 11.5,
    fontWeight: "700",
    marginRight: 8,
  },
  diffStatsCounts: {
    flexDirection: "row",
    gap: 6,
  },
  diffStatAdd: {
    color: "#2e8b38",
    fontSize: 12,
    fontWeight: "900",
  },
  diffStatDel: {
    color: "#d94b34",
    fontSize: 12,
    fontWeight: "900",
  },
  diffDetailContent: {
    gap: 10,
  },
  detailActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  historyDiffFile: {
    backgroundColor: "#f8f1e5",
    borderColor: "#25231f",
    borderRadius: 12,
    borderWidth: 2,
    gap: 8,
    padding: 10,
  },
});
