// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/documentprocessor/v1/document_processor.proto

package documentprocessorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProcessRequest_Start
	//	*ProcessRequest_Content
	//	*ProcessRequest_Completed
	Payload       isProcessRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetPayload() isProcessRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProcessRequest) GetStart() *ProcessStart {
	if x != nil {
		if x, ok := x.Payload.(*ProcessRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ProcessRequest) GetContent() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ProcessRequest_Content); ok {
			return x.Content
		}
	}
	return nil
}

func (x *ProcessRequest) GetCompleted() *ProcessInputCompleted {
	if x != nil {
		if x, ok := x.Payload.(*ProcessRequest_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

type isProcessRequest_Payload interface {
	isProcessRequest_Payload()
}

type ProcessRequest_Start struct {
	Start *ProcessStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ProcessRequest_Content struct {
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3,oneof"`
}

type ProcessRequest_Completed struct {
	Completed *ProcessInputCompleted `protobuf:"bytes,3,opt,name=completed,proto3,oneof"`
}

func (*ProcessRequest_Start) isProcessRequest_Payload() {}

func (*ProcessRequest_Content) isProcessRequest_Payload() {}

func (*ProcessRequest_Completed) isProcessRequest_Payload() {}

type ProcessStart struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentVersion int64                  `protobuf:"varint,3,opt,name=document_version,json=documentVersion,proto3" json:"document_version,omitempty"`
	ContentType     string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ParsingProfile  *ParsingProfile        `protobuf:"bytes,5,opt,name=parsing_profile,json=parsingProfile,proto3" json:"parsing_profile,omitempty"`
	ChunkingProfile *ChunkingProfile       `protobuf:"bytes,6,opt,name=chunking_profile,json=chunkingProfile,proto3" json:"chunking_profile,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessStart) Reset() {
	*x = ProcessStart{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStart) ProtoMessage() {}

func (x *ProcessStart) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStart.ProtoReflect.Descriptor instead.
func (*ProcessStart) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessStart) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProcessStart) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ProcessStart) GetDocumentVersion() int64 {
	if x != nil {
		return x.DocumentVersion
	}
	return 0
}

func (x *ProcessStart) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ProcessStart) GetParsingProfile() *ParsingProfile {
	if x != nil {
		return x.ParsingProfile
	}
	return nil
}

func (x *ProcessStart) GetChunkingProfile() *ChunkingProfile {
	if x != nil {
		return x.ChunkingProfile
	}
	return nil
}

type ProcessInputCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInputCompleted) Reset() {
	*x = ProcessInputCompleted{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInputCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInputCompleted) ProtoMessage() {}

func (x *ProcessInputCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInputCompleted.ProtoReflect.Descriptor instead.
func (*ProcessInputCompleted) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{2}
}

type ParsingProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParserId      string                 `protobuf:"bytes,3,opt,name=parser_id,json=parserId,proto3" json:"parser_id,omitempty"`
	ParserVersion string                 `protobuf:"bytes,4,opt,name=parser_version,json=parserVersion,proto3" json:"parser_version,omitempty"`
	Ocr           bool                   `protobuf:"varint,5,opt,name=ocr,proto3" json:"ocr,omitempty"`
	Options       map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsingProfile) Reset() {
	*x = ParsingProfile{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsingProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsingProfile) ProtoMessage() {}

func (x *ParsingProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsingProfile.ProtoReflect.Descriptor instead.
func (*ParsingProfile) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{3}
}

func (x *ParsingProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ParsingProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParsingProfile) GetParserId() string {
	if x != nil {
		return x.ParserId
	}
	return ""
}

func (x *ParsingProfile) GetParserVersion() string {
	if x != nil {
		return x.ParserVersion
	}
	return ""
}

func (x *ParsingProfile) GetOcr() bool {
	if x != nil {
		return x.Ocr
	}
	return false
}

func (x *ParsingProfile) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ChunkingProfile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StrategyId      string                 `protobuf:"bytes,3,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	StrategyVersion string                 `protobuf:"bytes,4,opt,name=strategy_version,json=strategyVersion,proto3" json:"strategy_version,omitempty"`
	MaxChunkSize    int32                  `protobuf:"varint,5,opt,name=max_chunk_size,json=maxChunkSize,proto3" json:"max_chunk_size,omitempty"`
	Overlap         int32                  `protobuf:"varint,6,opt,name=overlap,proto3" json:"overlap,omitempty"`
	Tokenizer       string                 `protobuf:"bytes,7,opt,name=tokenizer,proto3" json:"tokenizer,omitempty"`
	Options         map[string]string      `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChunkingProfile) Reset() {
	*x = ChunkingProfile{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkingProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkingProfile) ProtoMessage() {}

func (x *ChunkingProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkingProfile.ProtoReflect.Descriptor instead.
func (*ChunkingProfile) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkingProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChunkingProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChunkingProfile) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *ChunkingProfile) GetStrategyVersion() string {
	if x != nil {
		return x.StrategyVersion
	}
	return ""
}

func (x *ChunkingProfile) GetMaxChunkSize() int32 {
	if x != nil {
		return x.MaxChunkSize
	}
	return 0
}

func (x *ChunkingProfile) GetOverlap() int32 {
	if x != nil {
		return x.Overlap
	}
	return 0
}

func (x *ChunkingProfile) GetTokenizer() string {
	if x != nil {
		return x.Tokenizer
	}
	return ""
}

func (x *ChunkingProfile) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ProcessEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProcessEvent_Metadata
	//	*ProcessEvent_ChunkBatch
	//	*ProcessEvent_Completed
	Payload       isProcessEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent) Reset() {
	*x = ProcessEvent{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent) ProtoMessage() {}

func (x *ProcessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessEvent) GetPayload() isProcessEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProcessEvent) GetMetadata() *ProcessMetadata {
	if x != nil {
		if x, ok := x.Payload.(*ProcessEvent_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *ProcessEvent) GetChunkBatch() *ChunkBatch {
	if x != nil {
		if x, ok := x.Payload.(*ProcessEvent_ChunkBatch); ok {
			return x.ChunkBatch
		}
	}
	return nil
}

func (x *ProcessEvent) GetCompleted() *ProcessCompleted {
	if x != nil {
		if x, ok := x.Payload.(*ProcessEvent_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

type isProcessEvent_Payload interface {
	isProcessEvent_Payload()
}

type ProcessEvent_Metadata struct {
	Metadata *ProcessMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type ProcessEvent_ChunkBatch struct {
	ChunkBatch *ChunkBatch `protobuf:"bytes,2,opt,name=chunk_batch,json=chunkBatch,proto3,oneof"`
}

type ProcessEvent_Completed struct {
	Completed *ProcessCompleted `protobuf:"bytes,3,opt,name=completed,proto3,oneof"`
}

func (*ProcessEvent_Metadata) isProcessEvent_Payload() {}

func (*ProcessEvent_ChunkBatch) isProcessEvent_Payload() {}

func (*ProcessEvent_Completed) isProcessEvent_Payload() {}

type ProcessMetadata struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RequestId               string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DocumentId              string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentVersion         int64                  `protobuf:"varint,3,opt,name=document_version,json=documentVersion,proto3" json:"document_version,omitempty"`
	ContentType             string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ParserId                string                 `protobuf:"bytes,5,opt,name=parser_id,json=parserId,proto3" json:"parser_id,omitempty"`
	ParserVersion           string                 `protobuf:"bytes,6,opt,name=parser_version,json=parserVersion,proto3" json:"parser_version,omitempty"`
	ChunkingStrategyId      string                 `protobuf:"bytes,7,opt,name=chunking_strategy_id,json=chunkingStrategyId,proto3" json:"chunking_strategy_id,omitempty"`
	ChunkingStrategyVersion string                 `protobuf:"bytes,8,opt,name=chunking_strategy_version,json=chunkingStrategyVersion,proto3" json:"chunking_strategy_version,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProcessMetadata) Reset() {
	*x = ProcessMetadata{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMetadata) ProtoMessage() {}

func (x *ProcessMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMetadata.ProtoReflect.Descriptor instead.
func (*ProcessMetadata) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProcessMetadata) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ProcessMetadata) GetDocumentVersion() int64 {
	if x != nil {
		return x.DocumentVersion
	}
	return 0
}

func (x *ProcessMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ProcessMetadata) GetParserId() string {
	if x != nil {
		return x.ParserId
	}
	return ""
}

func (x *ProcessMetadata) GetParserVersion() string {
	if x != nil {
		return x.ParserVersion
	}
	return ""
}

func (x *ProcessMetadata) GetChunkingStrategyId() string {
	if x != nil {
		return x.ChunkingStrategyId
	}
	return ""
}

func (x *ProcessMetadata) GetChunkingStrategyVersion() string {
	if x != nil {
		return x.ChunkingStrategyVersion
	}
	return ""
}

type ChunkBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*ChunkDraft          `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkBatch) Reset() {
	*x = ChunkBatch{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkBatch) ProtoMessage() {}

func (x *ChunkBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkBatch.ProtoReflect.Descriptor instead.
func (*ChunkBatch) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkBatch) GetChunks() []*ChunkDraft {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type ChunkDraft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ordinal       int32                  `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	StartOffset   int64                  `protobuf:"varint,3,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset     int64                  `protobuf:"varint,4,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	SourcePage    int32                  `protobuf:"varint,5,opt,name=source_page,json=sourcePage,proto3" json:"source_page,omitempty"`
	SourceHeading string                 `protobuf:"bytes,6,opt,name=source_heading,json=sourceHeading,proto3" json:"source_heading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkDraft) Reset() {
	*x = ChunkDraft{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkDraft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkDraft) ProtoMessage() {}

func (x *ChunkDraft) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkDraft.ProtoReflect.Descriptor instead.
func (*ChunkDraft) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{8}
}

func (x *ChunkDraft) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *ChunkDraft) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChunkDraft) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *ChunkDraft) GetEndOffset() int64 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *ChunkDraft) GetSourcePage() int32 {
	if x != nil {
		return x.SourcePage
	}
	return 0
}

func (x *ChunkDraft) GetSourceHeading() string {
	if x != nil {
		return x.SourceHeading
	}
	return ""
}

type ProcessCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkCount    int32                  `protobuf:"varint,1,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	Warnings      []string               `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessCompleted) Reset() {
	*x = ProcessCompleted{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCompleted) ProtoMessage() {}

func (x *ProcessCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCompleted.ProtoReflect.Descriptor instead.
func (*ProcessCompleted) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessCompleted) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *ProcessCompleted) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{10}
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	WorkerId        string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HealthResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{12}
}

type CapabilitiesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion    string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Parsers            []*Capability          `protobuf:"bytes,2,rep,name=parsers,proto3" json:"parsers,omitempty"`
	ChunkingStrategies []*Capability          `protobuf:"bytes,3,rep,name=chunking_strategies,json=chunkingStrategies,proto3" json:"chunking_strategies,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{13}
}

func (x *CapabilitiesResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetParsers() []*Capability {
	if x != nil {
		return x.Parsers
	}
	return nil
}

func (x *CapabilitiesResponse) GetChunkingStrategies() []*Capability {
	if x != nil {
		return x.ChunkingStrategies
	}
	return nil
}

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{14}
}

func (x *Capability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Capability) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{15}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_documentprocessor_v1_document_processor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{16}
}

var File_api_documentprocessor_v1_document_processor_proto protoreflect.FileDescriptor

const file_api_documentprocessor_v1_document_processor_proto_rawDesc = "" +
	"\n" +
	"1api/documentprocessor/v1/document_processor.proto\x12\x19myai.documentprocessor.v1\"\xca\x01\n" +
	"\x0eProcessRequest\x12?\n" +
	"\x05start\x18\x01 \x01(\v2'.myai.documentprocessor.v1.ProcessStartH\x00R\x05start\x12\x1a\n" +
	"\acontent\x18\x02 \x01(\fH\x00R\acontent\x12P\n" +
	"\tcompleted\x18\x03 \x01(\v20.myai.documentprocessor.v1.ProcessInputCompletedH\x00R\tcompletedB\t\n" +
	"\apayload\"\xc7\x02\n" +
	"\fProcessStart\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12)\n" +
	"\x10document_version\x18\x03 \x01(\x03R\x0fdocumentVersion\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12R\n" +
	"\x0fparsing_profile\x18\x05 \x01(\v2).myai.documentprocessor.v1.ParsingProfileR\x0eparsingProfile\x12U\n" +
	"\x10chunking_profile\x18\x06 \x01(\v2*.myai.documentprocessor.v1.ChunkingProfileR\x0fchunkingProfile\"\x17\n" +
	"\x15ProcessInputCompleted\"\x98\x02\n" +
	"\x0eParsingProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparser_id\x18\x03 \x01(\tR\bparserId\x12%\n" +
	"\x0eparser_version\x18\x04 \x01(\tR\rparserVersion\x12\x10\n" +
	"\x03ocr\x18\x05 \x01(\bR\x03ocr\x12P\n" +
	"\aoptions\x18\x06 \x03(\v26.myai.documentprocessor.v1.ParsingProfile.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x02\n" +
	"\x0fChunkingProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vstrategy_id\x18\x03 \x01(\tR\n" +
	"strategyId\x12)\n" +
	"\x10strategy_version\x18\x04 \x01(\tR\x0fstrategyVersion\x12$\n" +
	"\x0emax_chunk_size\x18\x05 \x01(\x05R\fmaxChunkSize\x12\x18\n" +
	"\aoverlap\x18\x06 \x01(\x05R\aoverlap\x12\x1c\n" +
	"\ttokenizer\x18\a \x01(\tR\ttokenizer\x12Q\n" +
	"\aoptions\x18\b \x03(\v27.myai.documentprocessor.v1.ChunkingProfile.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x01\n" +
	"\fProcessEvent\x12H\n" +
	"\bmetadata\x18\x01 \x01(\v2*.myai.documentprocessor.v1.ProcessMetadataH\x00R\bmetadata\x12H\n" +
	"\vchunk_batch\x18\x02 \x01(\v2%.myai.documentprocessor.v1.ChunkBatchH\x00R\n" +
	"chunkBatch\x12K\n" +
	"\tcompleted\x18\x03 \x01(\v2+.myai.documentprocessor.v1.ProcessCompletedH\x00R\tcompletedB\t\n" +
	"\apayload\"\xd1\x02\n" +
	"\x0fProcessMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12)\n" +
	"\x10document_version\x18\x03 \x01(\x03R\x0fdocumentVersion\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tparser_id\x18\x05 \x01(\tR\bparserId\x12%\n" +
	"\x0eparser_version\x18\x06 \x01(\tR\rparserVersion\x120\n" +
	"\x14chunking_strategy_id\x18\a \x01(\tR\x12chunkingStrategyId\x12:\n" +
	"\x19chunking_strategy_version\x18\b \x01(\tR\x17chunkingStrategyVersion\"K\n" +
	"\n" +
	"ChunkBatch\x12=\n" +
	"\x06chunks\x18\x01 \x03(\v2%.myai.documentprocessor.v1.ChunkDraftR\x06chunks\"\xc4\x01\n" +
	"\n" +
	"ChunkDraft\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\x05R\aordinal\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12!\n" +
	"\fstart_offset\x18\x03 \x01(\x03R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x04 \x01(\x03R\tendOffset\x12\x1f\n" +
	"\vsource_page\x18\x05 \x01(\x05R\n" +
	"sourcePage\x12%\n" +
	"\x0esource_heading\x18\x06 \x01(\tR\rsourceHeading\"O\n" +
	"\x10ProcessCompleted\x12\x1f\n" +
	"\vchunk_count\x18\x01 \x01(\x05R\n" +
	"chunkCount\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings\"\x0f\n" +
	"\rHealthRequest\"p\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\"\x15\n" +
	"\x13CapabilitiesRequest\"\xda\x01\n" +
	"\x14CapabilitiesResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12?\n" +
	"\aparsers\x18\x02 \x03(\v2%.myai.documentprocessor.v1.CapabilityR\aparsers\x12V\n" +
	"\x13chunking_strategies\x18\x03 \x03(\v2%.myai.documentprocessor.v1.CapabilityR\x12chunkingStrategies\"6\n" +
	"\n" +
	"Capability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse2\xbd\x03\n" +
	"\x18DocumentProcessorService\x12i\n" +
	"\x0fProcessDocument\x12).myai.documentprocessor.v1.ProcessRequest\x1a'.myai.documentprocessor.v1.ProcessEvent(\x010\x01\x12]\n" +
	"\x06Health\x12(.myai.documentprocessor.v1.HealthRequest\x1a).myai.documentprocessor.v1.HealthResponse\x12r\n" +
	"\x0fGetCapabilities\x12..myai.documentprocessor.v1.CapabilitiesRequest\x1a/.myai.documentprocessor.v1.CapabilitiesResponse\x12c\n" +
	"\bShutdown\x12*.myai.documentprocessor.v1.ShutdownRequest\x1a+.myai.documentprocessor.v1.ShutdownResponseBAZ?myai/core/adapter/documentprocessor/grpc/pb;documentprocessorv1b\x06proto3"

var (
	file_api_documentprocessor_v1_document_processor_proto_rawDescOnce sync.Once
	file_api_documentprocessor_v1_document_processor_proto_rawDescData []byte
)

func file_api_documentprocessor_v1_document_processor_proto_rawDescGZIP() []byte {
	file_api_documentprocessor_v1_document_processor_proto_rawDescOnce.Do(func() {
		file_api_documentprocessor_v1_document_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_documentprocessor_v1_document_processor_proto_rawDesc), len(file_api_documentprocessor_v1_document_processor_proto_rawDesc)))
	})
	return file_api_documentprocessor_v1_document_processor_proto_rawDescData
}

var file_api_documentprocessor_v1_document_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_documentprocessor_v1_document_processor_proto_goTypes = []any{
	(*ProcessRequest)(nil),        // 0: myai.documentprocessor.v1.ProcessRequest
	(*ProcessStart)(nil),          // 1: myai.documentprocessor.v1.ProcessStart
	(*ProcessInputCompleted)(nil), // 2: myai.documentprocessor.v1.ProcessInputCompleted
	(*ParsingProfile)(nil),        // 3: myai.documentprocessor.v1.ParsingProfile
	(*ChunkingProfile)(nil),       // 4: myai.documentprocessor.v1.ChunkingProfile
	(*ProcessEvent)(nil),          // 5: myai.documentprocessor.v1.ProcessEvent
	(*ProcessMetadata)(nil),       // 6: myai.documentprocessor.v1.ProcessMetadata
	(*ChunkBatch)(nil),            // 7: myai.documentprocessor.v1.ChunkBatch
	(*ChunkDraft)(nil),            // 8: myai.documentprocessor.v1.ChunkDraft
	(*ProcessCompleted)(nil),      // 9: myai.documentprocessor.v1.ProcessCompleted
	(*HealthRequest)(nil),         // 10: myai.documentprocessor.v1.HealthRequest
	(*HealthResponse)(nil),        // 11: myai.documentprocessor.v1.HealthResponse
	(*CapabilitiesRequest)(nil),   // 12: myai.documentprocessor.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),  // 13: myai.documentprocessor.v1.CapabilitiesResponse
	(*Capability)(nil),            // 14: myai.documentprocessor.v1.Capability
	(*ShutdownRequest)(nil),       // 15: myai.documentprocessor.v1.ShutdownRequest
	(*ShutdownResponse)(nil),      // 16: myai.documentprocessor.v1.ShutdownResponse
	nil,                           // 17: myai.documentprocessor.v1.ParsingProfile.OptionsEntry
	nil,                           // 18: myai.documentprocessor.v1.ChunkingProfile.OptionsEntry
}
var file_api_documentprocessor_v1_document_processor_proto_depIdxs = []int32{
	1,  // 0: myai.documentprocessor.v1.ProcessRequest.start:type_name -> myai.documentprocessor.v1.ProcessStart
	2,  // 1: myai.documentprocessor.v1.ProcessRequest.completed:type_name -> myai.documentprocessor.v1.ProcessInputCompleted
	3,  // 2: myai.documentprocessor.v1.ProcessStart.parsing_profile:type_name -> myai.documentprocessor.v1.ParsingProfile
	4,  // 3: myai.documentprocessor.v1.ProcessStart.chunking_profile:type_name -> myai.documentprocessor.v1.ChunkingProfile
	17, // 4: myai.documentprocessor.v1.ParsingProfile.options:type_name -> myai.documentprocessor.v1.ParsingProfile.OptionsEntry
	18, // 5: myai.documentprocessor.v1.ChunkingProfile.options:type_name -> myai.documentprocessor.v1.ChunkingProfile.OptionsEntry
	6,  // 6: myai.documentprocessor.v1.ProcessEvent.metadata:type_name -> myai.documentprocessor.v1.ProcessMetadata
	7,  // 7: myai.documentprocessor.v1.ProcessEvent.chunk_batch:type_name -> myai.documentprocessor.v1.ChunkBatch
	9,  // 8: myai.documentprocessor.v1.ProcessEvent.completed:type_name -> myai.documentprocessor.v1.ProcessCompleted
	8,  // 9: myai.documentprocessor.v1.ChunkBatch.chunks:type_name -> myai.documentprocessor.v1.ChunkDraft
	14, // 10: myai.documentprocessor.v1.CapabilitiesResponse.parsers:type_name -> myai.documentprocessor.v1.Capability
	14, // 11: myai.documentprocessor.v1.CapabilitiesResponse.chunking_strategies:type_name -> myai.documentprocessor.v1.Capability
	0,  // 12: myai.documentprocessor.v1.DocumentProcessorService.ProcessDocument:input_type -> myai.documentprocessor.v1.ProcessRequest
	10, // 13: myai.documentprocessor.v1.DocumentProcessorService.Health:input_type -> myai.documentprocessor.v1.HealthRequest
	12, // 14: myai.documentprocessor.v1.DocumentProcessorService.GetCapabilities:input_type -> myai.documentprocessor.v1.CapabilitiesRequest
	15, // 15: myai.documentprocessor.v1.DocumentProcessorService.Shutdown:input_type -> myai.documentprocessor.v1.ShutdownRequest
	5,  // 16: myai.documentprocessor.v1.DocumentProcessorService.ProcessDocument:output_type -> myai.documentprocessor.v1.ProcessEvent
	11, // 17: myai.documentprocessor.v1.DocumentProcessorService.Health:output_type -> myai.documentprocessor.v1.HealthResponse
	13, // 18: myai.documentprocessor.v1.DocumentProcessorService.GetCapabilities:output_type -> myai.documentprocessor.v1.CapabilitiesResponse
	16, // 19: myai.documentprocessor.v1.DocumentProcessorService.Shutdown:output_type -> myai.documentprocessor.v1.ShutdownResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_documentprocessor_v1_document_processor_proto_init() }
func file_api_documentprocessor_v1_document_processor_proto_init() {
	if File_api_documentprocessor_v1_document_processor_proto != nil {
		return
	}
	file_api_documentprocessor_v1_document_processor_proto_msgTypes[0].OneofWrappers = []any{
		(*ProcessRequest_Start)(nil),
		(*ProcessRequest_Content)(nil),
		(*ProcessRequest_Completed)(nil),
	}
	file_api_documentprocessor_v1_document_processor_proto_msgTypes[5].OneofWrappers = []any{
		(*ProcessEvent_Metadata)(nil),
		(*ProcessEvent_ChunkBatch)(nil),
		(*ProcessEvent_Completed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_documentprocessor_v1_document_processor_proto_rawDesc), len(file_api_documentprocessor_v1_document_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_documentprocessor_v1_document_processor_proto_goTypes,
		DependencyIndexes: file_api_documentprocessor_v1_document_processor_proto_depIdxs,
		MessageInfos:      file_api_documentprocessor_v1_document_processor_proto_msgTypes,
	}.Build()
	File_api_documentprocessor_v1_document_processor_proto = out.File
	file_api_documentprocessor_v1_document_processor_proto_goTypes = nil
	file_api_documentprocessor_v1_document_processor_proto_depIdxs = nil
}
